[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
test = "test-foundry"
cache_path = "cache-foundry"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"

# Use `node_modules` as the OZ source of truth.
remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/"
]

